# ------------------------------------
# Development Stage
# ------------------------------------
FROM node:20-alpine AS dev-stage

# 設定工作目錄
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --force